services:
  - type: web
    name: byte-stream
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm run db:push && npm run start
    envVars:
      - key: NODE_ENV
        value: development
      - key: DATABASE_URL
        fromDatabase:
          name: byte-stream-db
          property: connectionString
      - key: SESSION_SECRET
        generateValue: true

databases:
  - name: byte-stream-db
    plan: free
    databaseName: bytestream
    user: bytestream
